
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: tuner_app_development
  username: Ros
  host: localhost

test:
  <<: *default
  database: tuner_app_test
  username: Ros
  host: localhost

#
production:
  <<: *default
  database: tuner_app_production
  username: Ros
  host: localhost
